### ISSUE TITLE
Error with expanded attribute in two pane. How I can expand more than one pane?

### ISSUE THREAD

**Issue by EricDosReis** [LukaszWatroba/v-accordion#18]
Hey, thanks for building this plugin!

I'm trying to do this, but an error occurs:

```html
<v-accordion class="vAccordion--default" multiple>

<!-- Pane One expanded -->
  <v-pane expanded>
    <v-pane-header>
      Pane header #1
    </v-pane-header>

    <v-pane-content>
      Pane content #1
    </v-pane-content>
  </v-pane>

<!-- Pane Two expanded too -->
  <v-pane expanded>
    <v-pane-header>
      Pane header #2
    </v-pane-header>

    <v-pane-content>
      Pane content #2
    </v-pane-content>
  </v-pane>

</v-accordion>
```

Error: The `multiple` attribute can't be found at AccordionDirectiveController.ctrl.addPane.

**Comment by LukaszWatroba** [comment]
Thanks @EricDosReis, I fixed that. Please, update the package to the latest release — [v1.2.9](https://github.com/LukaszWatroba/v-accordion/releases/tag/v1.2.9)

**Comment by EricDosReis** [comment]
Thanks @LukaszWatroba

**Comment by jam2206401** [comment]
@LukaszWatroba , I'm still having the very same error in v1.2.9 
![image](https://cloud.githubusercontent.com/assets/11268303/18875245/918f0aea-84cd-11e6-9eae-b299cd7789f5.png)

**Comment by jam2206401** [comment]
@LukaszWatroba I'm sorry Lukas. When I added the **multiple** attribute to v-accordion, problem solved.  There seems no problem at all.
